-- Create categories table
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- Create processes table
CREATE TABLE IF NOT EXISTS public.processes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- Create compositions table
CREATE TABLE IF NOT EXISTS public.compositions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- Create products table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  dimensions TEXT,
  material TEXT,
  technique TEXT,
  status TEXT,
  "lifestyleImage" TEXT,
  "productImage" TEXT,
  price DECIMAL(10, 2),
  "showPrice" BOOLEAN DEFAULT true,
  category TEXT,
  process TEXT,
  availability TEXT,
  composition TEXT,
  "weaveHarvest" TEXT,
  "weaveHarvestOrigin" TEXT,
  "packagingDelivery" TEXT,
  "packagingDeliveryCourier" TEXT,
  "galleryImages" TEXT
);

-- Enable Row Level Security (optional but recommended)
-- ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.processes ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.compositions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- If you enable RLS, you will need to add policies for reading/writing. 
-- For a simple admin backend, you can leave it disabled, 
-- or enable it and create a policy that allows the service_role to bypass RLS.
